### PR TITLE
fix (localpv): CSIStorageClass shows zero if SC "poolname" includes dataset path

### LINKED ISSUE #392: GetCapacity reports zero when using non-root dataset
**What steps did you take and what happened:**

I created a StorageClass with the poolname "rpool/LOCALPV", and volumeBindingMode: WaitForFirstConsumer, then tried to start pods with PVCs using this SC.

**What did you expect to happen:**

CSIStorageCapacity objects containing non-zero "capacity" field should have been created.

**The output of the following commands will help us better understand what's going on**:

The capacities can be checked quickly:

`kubectl get -A CSIStorageCapacity -o custom-columns=NODE:nodeTopology.matchLabels.kubernetes\\.io/hostname,NAME:metadata.name,CAPACITY:capacity`

Logs doesn't contain anything helpful here.

**Anything else you would like to add:**

In pkg/driver/controller.go there's the function called "GetCapacity" that reports node storage capacity. This function returns 0 when the "poolname" attribute of the StorageClass contains anything but a ZFS pool name, e.g. "rpool".

However the documentation states that I can use a child dataset too, e.g. "rpool/LOCALPV".

If I create a storage class with the above path and volumeBindingMode: WaitForFirstConsumer, kube-scheduler will report that it cannot schedule the pods due to insufficient storage capacity.

**Environment:**
- ZFS-LocalPV version: 1.9.3
- Kubernetes version (use `kubectl version`): 1.22.2
- Kubernetes installer & version: kubeadm 1.22.2
- Cloud provider or hardware configuration: 3 x Raspberry Pi 4 8G RAM, also a desktop with i10900K & 64G RAM
- OS (e.g. from `/etc/os-release`): Ubuntu "Focal" 20.04.3 in both cases

**Fix**

PR coming soon.

### PR DESCRIPTION
**Pull request by netom**
Signed-off-by: Fábián Tamás László <giganetom@gmail.com>

**Why is this PR required? What issue does it fix?**:

It fixes #392 "GetCapacity reports zero when using non-root dataset"

**What this PR does?**:

Amends pkg/driver/controller.go to return the root dataset's capacity when using a child dataset as the pool name.

I'm aware that this is not the ideal solution, as the child dataset may offer less capacitry than the whole pool, but this is most definitely better than returning a straigh zero like it's now.

The situation could further be improved if the Node could return the capacity of a child dataset.

**Does this PR require any upgrade changes?**:

No, this is just a simple fix in the capacity calculation.

**If the changes in this PR are manually verified, list down the scenarios covered:**:

I've manually verified that the storage capacity returns the pool's capacity when a child dataset is used, and also when the "poolname" is really just the pool's name.

**Any additional information for your reviewer?** :

This is just a small, standalone fix, not part of anything greater.

### CODE REVIEW

File: pkg/driver/controller.go [hunk 1]
```diff
@@ -873,8 +873,18 @@ func (cs *controller) GetCapacity(
 	}
 
 	zfsNodesCache := cs.zfsNodeInformer.GetIndexer()
+
 	params := req.GetParameters()
+
 	poolParam := helpers.GetInsensitiveParameter(&params, "poolname")
+	poolParamPool, _ := func() (string, string) {
```
Comment (pawanpraka1) [inline pkg/driver/controller.go]: Can we add a comment explaining why need to parse the pool name.

File: pkg/driver/controller.go [hunk 2]
```diff
@@ -892,7 +902,7 @@ func (cs *controller) GetCapacity(
 		// See https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1472-storage-capacity-tracking#available-capacity-vs-maximum-volume-size &
 		// https://github.com/container-storage-interface/spec/issues/432 for more details
 		for _, zpool := range zfsNode.Pools {
-			if zpool.Name != poolParam {
+			if zpool.Name != poolParamPool {
```
Comment (pawanpraka1) [inline pkg/driver/controller.go]: Can we rename poolParamPool to poolname?

**Review by pawanpraka1 — COMMENTED** [review]
Looks good. Have given some minor comments. Thanks for this PR @netom.

File: pkg/driver/controller.go (hunk 1 above)
Comment (netom) [reply pkg/driver/controller.go]: Sure, no problem. I'll update the PR quick.

File: pkg/driver/controller.go (hunk 2 above)
Comment (netom) [reply pkg/driver/controller.go]: Of course. Will do that shortly.

**Review by pawanpraka1 — APPROVED** [review]
looks good.
