### PR TITLE
fix: handle filesystem shutdown more gracefully

### LINKED ISSUE #615: NodeUnpublish stuck when the filesystem is shutdown
**What steps did you take and what happened:**
When some goes awry there's a chance a filesystem may shutdown, example: #614
In this case, deleting the Pod is stuck because `NodeUnpublish` is stuck.

**What did you expect to happen:**
Expect to be able to delete the pod.

**The output of the following commands will help us better understand what's going on**:

* `kubectl logs -f openebs-zfs-node-[xxxx] -n openebs -c openebs-zfs-plugin`
```text
I0121 15:24:24.353104       1 grpc.go:72] GRPC call: /csi.v1.Node/NodeUnpublishVolume requests {"target_path":"/var/lib/kubelet/pods/cef1876f-ff31-4d5e-a8c7-d8c8c1243138/volumes/kubernetes.io~csi/pvc-f5e204ba-3797-47f9-bfe7-236d078292f7/mount","volume_id":"pvc-f5e204ba-3797-47f9-bfe7-236d078292f7"}
E0121 15:24:24.356452       1 grpc.go:79] GRPC error: rpc error: code = Internal desc = unable to umount the volume pvc-f5e204ba-3797-47f9-bfe7-236d078292f7 err : Error checking if path exists: stat /var/lib/kubelet/pods/cef1876f-ff31-4d5e-a8c7-d8c8c1243138/volumes/kubernetes.io~csi/pvc-f5e204ba-3797-47f9-bfe7-236d078292f7/mount: input/output error
I0121 15:24:24.956720       1 grpc.go:72] GRPC call: /csi.v1.Node/NodeUnpublishVolume requests {"target_path":"/var/lib/kubelet/pods/cef1876f-ff31-4d5e-a8c7-d8c8c1243138/volumes/kubernetes.io~csi/pvc-f5e204ba-3797-47f9-bfe7-236d078292f7/mount","volume_id":"pvc-f5e204ba-3797-47f9-bfe7-236d078292f7"}
E0121 15:24:24.961777       1 grpc.go:79] GRPC error: rpc error: code = Internal desc = unable to umount the volume pvc-f5e204ba-3797-47f9-bfe7-236d078292f7 err : Error checking if path exists: stat /var/lib/kubelet/pods/cef1876f-ff31-4d5e-a8c7-d8c8c1243138/volumes/kubernetes.io~csi/pvc-f5e204ba-3797-47f9-bfe7-236d078292f7/mount: input/output error
I0121 15:24:25.964596       1 grpc.go:72] GRPC call: /csi.v1.Node/NodeUnpublishVolume requests {"target_path":"/var/lib/kubelet/pods/cef1876f-ff31-4d5e-a8c7-d8c8c1243138/volumes/kubernetes.io~csi/pvc-f5e204ba-3797-47f9-bfe7-236d078292f7/mount","volume_id":"pvc-f5e204ba-3797-47f9-bfe7-236d078292f7"}
E0121 15:24:25.968437       1 grpc.go:79] GRPC error: rpc error: code = Internal desc = unable to umount the volume pvc-f5e204ba-3797-47f9-bfe7-236d078292f7 err : Error checking if path exists: stat /var/lib/kubelet/pods/cef1876f-ff31-4d5e-a8c7-d8c8c1243138/volumes/kubernetes.io~csi/pvc-f5e204ba-3797-47f9-bfe7-236d078292f7/mount: input/output error
```

**Environment:**
- LocalPV-ZFS version: `2.7.0-develop`
- Cloud provider or hardware configuration: `qemu vm x86_64`
- OS (e.g. from `/etc/os-release`): `NixOS 24.11 (Vicuna)`
- Kernel version: `Linux nixos 6.6.69`

### PR DESCRIPTION
**Pull request by tiagolobocastro**
## Pull Request template

Please, go through these steps before you submit a PR.

**Why is this PR required? What issue does it fix?**:

Resolves #615

**What this PR does?**:

Allows for volumes to be gracefully unpublished, even in case of filesystem shutdown.

**Does this PR require any upgrade changes?**: No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Fixes #615 
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [x] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/website is used to track them:

### CODE REVIEW

File: pkg/zfs/mount.go [hunk 1]
```diff
@@ -91,7 +93,10 @@ func UmountVolume(vol *apis.ZFSVolume, targetPath string,
 	}
 
 	if pathExists, pathErr := mount.PathExists(targetPath); pathErr != nil {
-		return fmt.Errorf("Error checking if path exists: %v", pathErr)
+		// If the mount is broken, unmount it since there's nothing else to do anyway
+		if !isBrokenMount(targetPath) {
+			return fmt.Errorf("Error checking if path exists: %v", pathErr)
```
Comment (niladrih) [inline pkg/zfs/mount.go:98]: This was already there. But it's definitely a bug, all logs must go via the central logger. This go module may or may not have a go routine feeding go standard library 'log' buffers to klog, but fmt is most certainly not getting the same tratement.
```suggestion
			return klog.Errorf("Error checking if path exists: %v", pathErr)
```

Comment (tiagolobocastro) [reply pkg/zfs/mount.go:98]: but this is returning the error not logging it

Comment (niladrih) [reply pkg/zfs/mount.go:98]: I was mistaken. I was under impression that fmt.Errorf prints and returns the length of the message byte slice.

**Review by niladrih — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
@mergify queue
